[package]
name = "rustyfuck"
description = "Yet another brainfuck interpreter on Rust"
authors = [ "Maksim Bengraf (OctoBanon) <me@octobanon.com>" ]
license = "Unlicense"
version = "1.0.2"
edition = "2021"