[package]
name = "rustyfuck"
description = "Yet another brainfuck interpreter on Rust"
authors = [ "Maksim Bengraf (OctoBanon) <octobanon@proton.me>" ]
license = "Unlicense"
version = "2.0.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.6.7", features = ["derive"] }

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
opt-level = 3